stadiums = {
    "0": "Manchester United",
    "1": "Liverpool",
    "2": "Manchester City",
    "3": "Chelsea",
    "4": "Arsenal",
    "5": "Tottenham Hotspur",
    "6": "Everton",
    "7": "Leicester City",
    "8": "Wolverhampton Wanderers",
    "9": "Newcastle United",
    "10": "Leeds United",
    "11": "Fulham",
    "12": "Sheffield United",
    "13": "Aston Villa",
    "14": "Crystal Palace",
    "15": "West Ham United",
    "16": "Burnley",
    "17": "Southampton",
    "18": "Brighton & Hove Albion",
    "19": "Brentford",
    "20": "AFC Bournemouth",
    "21": "Cardiff City",
    "22": "Swansea City",
    "23": "Middlesbrough",
    "24": "Derby County",
    "25": "Ipswich Town",
    "26": "Blackburn Rovers",
    "27": "Bristol City",
    "28": "Nottingham Forest",
    "29": "Preston North End",
    "30": "Luton Town",
    "31": "Charlton Athletic",
    "32": "Wigan Athletic",
    "33": "Sheffield Wednesday",
    "34": "Hull City",
    "35": "Queens Park Rangers",
    "36": "Stoke City",
    "37": "West Bromwich Albion",
    "38": "Sunderland",
    "39": "Coventry City",
    "40": "Watford",
    "41": "Norwich City",
    "42": "Plymouth Argyle",
    "43": "Huddersfield Town",
    "44": "Rotherham United",
    "45": "Millwall",
    "46": "Reading",
    "47": "Birmingham City",
    "48": "Wycombe Wanderers",
    "49": "Doncaster Rovers",
    "50": "Portsmouth",
    "51": "Milton Keynes Dons",
    "52": "Tranmere Rovers",
    "53": "Oxford United",
    "54": "Bradford City",
    "55": "Walsall",
    "56": "Grimsby Town",
    "57": "Carlisle United",
    "58": "Northampton Town",
    "59": "Cheltenham Town",
    "60": "Crewe Alexandra",
    "61": "Notts County",
    "62": "Lincoln City",
    "63": "Mansfield Town",
    "64": "Barrow",
    "65": "Bolton Wanderers",
    "66": "Peterborough United",
    "67": "Barnsley",
    "68": "Stevenage",
    "69": "Blackpool",
    "70": "Bristol Rovers",
    "71": "Port Vale",
    "72": "Shrewsbury Town",
    "73": "Burton Albion",
    "74": "Cambridge United",
    "75": "Exeter City",
    "76": "Fleetwood Town",
    "77": "Leyton Orient",
    "78": "Stockport County",
    "79": "Wrexham",
    "80": "AFC Wimbledon",
    "81": "Crawley Town",
    "82": "Accrington Stanley",
    "83": "Gillingham",
    "84": "Harrogate Town",
    "85": "Swindon Town",
    "86": "Morecambe",
    "87": "Newport County",
    "88": "Salford City",
    "89": "Colchester United",
    "90": "Forest Green Rovers",
    "91": "Sutton United",
}

leagues = {
    "Manchester United": "Premier League",
    "Liverpool": "Premier League",
    "Manchester City": "Premier League",
    "Chelsea": "Premier League",
    "Arsenal": "Premier League",
    "Tottenham Hotspur": "Premier League",
    "Everton": "Premier League",
    "Leicester City": "Championship",
    "Wolverhampton Wanderers": "Premier League",
    "Newcastle United": "Premier League",
    "Leeds United": "Championship",
    "Fulham": "Premier League",
    "Sheffield United": "Premier League",
    "Aston Villa": "Premier League",
    "Crystal Palace": "Premier League",
    "West Ham United": "Premier League",
    "Burnley": "Premier League",
    "Southampton": "Championship",
    "Brighton & Hove Albion": "Premier League",
    "Brentford": "Premier League",
    "AFC Bournemouth": "Premier League",
    "Cardiff City": "Championship",
    "Swansea City": "Championship",
    "Middlesbrough": "Championship",
    "Derby County": "League One",
    "Ipswich Town": "Championship",
    "Blackburn Rovers": "Championship",
    "Bristol City": "Championship",
    "Nottingham Forest": "Premier League",
    "Preston North End": "Championship",
    "Luton Town": "Premier League",
    "Charlton Athletic": "League One",
    "Wigan Athletic": "League One",
    "Sheffield Wednesday": "Championship",
    "Hull City": "Championship",
    "Queens Park Rangers": "Championship",
    "Stoke City": "Championship",
    "West Bromwich Albion": "Championship",
    "Sunderland": "Championship",
    "Coventry City": "Championship",
    "Watford": "Championship",
    "Norwich City": "Championship",
    "Plymouth Argyle": "Championship",
    "Huddersfield Town": "Championship",
    "Rotherham United": "Championship",
    "Millwall": "Championship",
    "Reading": "League One",
    "Birmingham City": "Championship",
    "Wycombe Wanderers": "League One",
    "Doncaster Rovers": "League Two",
    "Portsmouth": "League One",
    "Milton Keynes Dons": "League Two",
    "Tranmere Rovers": "League Two",
    "Oxford United": "League One",
    "Bradford City": "League Two",
    "Walsall": "League Two",
    "Grimsby Town": "League Two",
    "Carlisle United": "League One",
    "Northampton Town": "League One",
    "Cheltenham Town": "League One",
    "Crewe Alexandra": "League Two",
    "Notts County": "League Two",
    "Lincoln City": "League One",
    "Mansfield Town": "League Two",
    "Barrow": "League Two",
    "Bolton Wanderers": "League One",
    "Peterborough United": "League One",
    "Barnsley": "League One",
    "Stevenage": "League One",
    "Blackpool": "League One",
    "Bristol Rovers": "League One",
    "Port Vale": "League One",
    "Shrewsbury Town": "League One",
    "Burton Albion": "League One",
    "Cambridge United": "League One",
    "Exeter City": "League One",
    "Fleetwood Town": "League One",
    "Leyton Orient": "League One",
    "Stockport County": "League Two",
    "Wrexham": "League Two",
    "AFC Wimbledon": "League Two",
    "Crawley Town": "League Two",
    "Accrington Stanley": "League Two",
    "Gillingham": "League Two",
    "Harrogate Town": "League Two",
    "Swindon Town": "League Two",
    "Morecambe": "League Two",
    "Newport County": "League Two",
    "Salford City": "League Two",
    "Colchester United": "League Two",
    "Forest Green Rovers": "League Two",
    "Sutton United": "League Two",
}